export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"
export const CLEAR_MODAL = "CLEAR_MODAL"
export const SET_MODAL = "SET_MODAL"
export const CLOSE_EDIT_FORM = "CLOSE_EDIT_FORM"
export const OPEN_EDIT_FORM = "OPEN_EDIT_FORM"
