export const SET_ATTACHMENTS = "SET_ATTACHMENTS"
export const FETCH_ATTACHMENTS = "FETCH_ATTACHMENTS"
export const ADD_ATTACHMENT = "ADD_ATTACHMENT"
export const DELETE_ATTACHMENT = "DELETE_ATTACHMENT"
export const UPDATE_ATTACHMENT = "UPDATE_ATTACHMENT"
export const CLEAR_ATTACHMENTS = "CLEAR_ATTACHMENTS"

